language: haskell

sudo: false

matrix:
  include:
    - env: CABALVER=1.24 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,happy-1.19.12,alex-3.2.5,libgtk2.0-dev,libgtk-3-dev], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,happy-1.19.12,alex-3.2.5,libgtk2.0-dev,libgtk-3-dev], sources: [hvr-ghc]}}
    - env: CABALVER=2.0 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.2,happy-1.19.12,alex-3.2.5,libgtk2.0-dev,libgtk-3-dev], sources: [hvr-ghc]}}
    - env: CABALVER=2.2 GHCVER=8.4.4
      addons: {apt: {packages: [cabal-install-2.2,ghc-8.4.4,happy-1.19.12,alex-3.2.5,libgtk2.0-dev,libgtk-3-dev], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.6.5
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.1,happy-1.19.12,alex-3.2.5,libgtk2.0-dev,libgtk-3-dev], sources: [hvr-ghc]}}
    - env: CABALVER=3.0 GHCVER=8.8.1
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.1,happy-1.19.12,alex-3.2.5,libgtk2.0-dev,libgtk-3-dev], sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head,ghc-head,happy-1.19.12,alex-3.2.5,libgtk2.0-dev,libgtk-3-dev],  sources: [hvr-ghc]}}
  allow_failures:
    - env: CABALVER=1.24 GHCVER=7.10.3
    - env: CABALVER=head GHCVER=head

before_install:
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.2.5/bin:/opt/happy/1.19.12/bin:$PATH

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal update
  - cabal install Cabal
  - cabal install haddock
  - haddock -V

script:
  - ./install-both.sh

notifications:
  irc:
    channels: "irc.freenode.net#gtk2hs"
    skip_join: true
  email: true
